apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
spec:
  containers:
    - name: alpine
      image: alpine
      args: 
        - /bin/sh
        - -c
        - touch /livenessPrope; sleep 30; rm -f /livenessPrope; sleep 600
      livenessProbe:
        exec:
         command:
            - cat
            - /livenessPrope