
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
    type: front-end
spec:
  template:
    metadata:
      name: nodeapp-pod
      labels:
       app: nodeapp
    spec:
      containers:
        - name: weguidetest
          image: httpd:2.4.58
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
