apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres
  storageClassName: standard
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres-pv-1
# spec:
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /mnt/data/postgres
#   storageClassName: standard
